### ISSUE TITLE
Import of transactional data fails after Resetting partition for dataSource

### ISSUE THREAD

**Issue by dcolleoni** [Systemorph/IFRS17CalculationEngine#122]
In Template project run Import/CloseImportTemplate
1. add some more imports: DataNode, DataNodeState, DataNodeParameter, Actuals,Cashflow,SimpleData
2. after all cells are executed included the reset in section 4 run an import of transactional data (CF). This fails with the following message.
![image](https://user-images.githubusercontent.com/103409906/206395624-9e78a23e-4cfc-4ecd-8413-4ff9828002af.png)
3. Run instead the DataNodeParameter or DataNodeState and that is successful
4. After point 3 import again transactional data (point 2) and the error is not present.

Importers should be successful in any order, starting from any state of the DataSource : partition set or not. 

Possible problem: some partition set is missing in the importers for Transactional data

**Comment by andrey-katz-systemorph** [comment]
After preliminary investigation I would say that the problem has to do with the way the opening format is defined in the calculation engine. In fact, the problem does not show up, if we import the data node format after setting the partitions to null. FYI: @dcolleoni
