### ISSUE TITLE
Distinguish Zeros from import in Scenario and Zero due to missing Data

### ISSUE THREAD

**Issue by calderinisystemorph** [Systemorph/IFRS17CalculationEngine#132]
In the implementation of Scenario Importers it was enabled to save zeros for RawVariable and IfrsVariable, due to fact that users may need to "suppress" some line in the Cashflow or Actuals. This feature led to an implementation which  is not optimal. Hence, is important to distinguish between a compact, meaningful set of zeros that are representative of the business logic and discard the rest.

**Comment by amuolo** [comment]
I think we can close this ticket because it has been solved with the PR #112 
@dcolleoni @calderinisystemorph
