### ISSUE TITLE
Track Activity log in the DB

### ISSUE THREAD

**Issue by dcolleoni** [Systemorph/IFRS17CalculationEngine#137]
Add records in DataModel 
Add method to populate the tables in the DB with the necessary data at the end of the activity.

**Comment by amuolo** [comment]
@dcolleoni @dtrzesniak which "necessary data" have to be uploaded to DB? Could we have a list here to facilitate the analysis of the linked PR?

**Comment by dtrzesniak** [comment]
> @dcolleoni @dtrzesniak which "necessary data" have to be uploaded to DB? Could we have a list here to facilitate the analysis of the linked PR?

We need to log the conditions to be able to reproduce the calculations.

Data inputs normally trigger many calculations, and we need to save various things. We need to ensure that whatever state we have, we are never inconsistent in the data --> showing outdated results. We have to also be careful here, as some updates should not trigger recalculation: example yield curves in the past.

We need to be able to show this though, and by looking at the logs any auditor is able to reproduce the numbers.

Not sure it answers what you asked.
