### ISSUE TITLE
Cleanups for Reports Notebook

### ISSUE THREAD

**Issue by amuolo** [Systemorph/IFRS17CalculationEngine#155]
This ticket is about a number of cleanups for the notebook Reports of the IFRS 17 Template Project: 
a. With the automatic height feature of the new reports we don't need anymore to specify with { Height } for all the reports.
b. The Actuarial Experience Adjustment has already the columns sliced by Amount Type, hence we can remove the suggestion in the commented part.

**Comment by dcolleoni** [comment]
Hi @amuolo,
about point b, the suggestion is not to add AmountType but to add GroupOfContract and AmountType. 
Adding AmountType after GroupOfContract allows the user to control the order of the sliced column and get a better understanding of the reported values. 

I suggest to remove point b from this issue or to reformulate to provide a better description of the suggested code.

**Comment by nnikolopoulos** [comment]
Hi both @amuolo @dcolleoni,
since an **automatic height feature** has already been added in the platform it seems reasonable for a `GroupDefaultExpand` feature to be requested as well from the platform. Do you agree?
