### ISSUE TITLE
Improve Activity log methods

### ISSUE THREAD

**Issue by dcolleoni** [Systemorph/IFRS17CalculationEngine#167]
Improvements on how the logs are stored in the DB:

**Comment by andrey-katz-systemorph** [comment]
Suggestions for improvement: 

1. If the import or export fail, they should not have a "fake" source Id. This should be null 
2. Change the API as suggested by @dtrzesniak : WithStoreActivityLog().ExecuteAsync()

**Comment by dcolleoni** [comment]
Further improvements on the code taken from comments in PR #178 

Can't you simplify this:

Add the "await DataSource.UpdateAsync(importFile.RepeatOnce());"," inside the try
Remove importSucceeded,
Add "activity = activity with {Category = "Import from File"};"," inside the try and catch --> you are creating activity twice (once to set SourceId, once to set Category).
Declare importFile inside the try
Extract the try/catch as method of type and pass the parameters to avoid the repetition of this code.
I have not thought it through, but I guess this should work and make the code leaner
