### ISSUE TITLE
Remove redundant specification on the Data Model

### ISSUE THREAD

**Issue by dtrzesniak** [Systemorph/IFRS17CalculationEngine#21]
See that we use defaults as much as possible.
Example, we don't need to define a Display order if the default is the one we want

public record AmountType : KeyedOrderedDimensionWithExternalId, IHierarchicalDimension
{
    [Display(Order = 10)]  -**_-> Not needed, over-specified_**
    [Dimension(typeof(AmountType))]
    public string Parent { get; init; }
    
    [Display(Order = 20)]
    [Dimension(typeof(PeriodType))]
    public PeriodType PeriodType { get; init; }
}

**Comment by tkukuljan** [comment]
The default ordering is not sufficient only for Export purposes. Therefore I plan to keep the order attributes only for the records that are exported (that are ReinsurancePortfolio, InsurancePortfolio, GroupOfReinsuranceContract, GroupOfInsuranceContract, DataNodeState, InterDataNodeParameter, SingleDataNodeParameter)
Is this how it should be done?
@dcolleoni @dcolleoni @amuolo

**Comment by dtrzesniak** [comment]
@tkukuljan @amuolo @dcolleoni . In V7, the order for the UI and Export was taken from the order the properties appear in the data model (top to bottom). It could be that in SMC the order is alphabetical instead, and then indeed the Display order would be needed.
However, IMO if the behavior is not the natural data model order, then we should request this change to to the platform.

**Comment by dtrzesniak** [comment]
I would remove everywhere where not needed. So, yes, for now keep only those needed for Export.
