### ISSUE TITLE
Reports(interactive and not) with projections Controller

### ISSUE THREAD

**Issue by dcolleoni** [Systemorph/IFRS17CalculationEngine#211]
Report controllers for projections.

**Comment by dcolleoni** [comment]
Increasing Priority to this item as it is important to define the dataModel around Values for IfrsVariable. 
This has high priority because it impacts data model of deployed systems in client applications.

**Comment by andrey-katz-systemorph** [comment]
I will summarize here the main goals of the ticket, please feel free to correct or add more things, it is a summary of all or discussions.

1. Rearrange projections into more natural and resourceful form than 13 different variables. Array is a natural suspect. The calculation and testing routine should be adjusted to fit this change.
2. Make sure that projections can appear in the reports, interactive and non interactive.  Display names should appear as in projection file. 
3. The user should be able to choose between  a report with no projections and the projections up to certain period, that should be controlled via a specific filter in non-interactive reports and a dedicated dropdown in the interactive one.   

FYI @dcolleoni @amuolo

**Comment by dcolleoni** [comment]
Decreasing the prio as the datamodel has been adapted. 
This issue only concerns reporting and thus becomes relevant when all projection computation is fully supported.
