### ISSUE TITLE
Demo Reinsurance Scenarios

### ISSUE THREAD

**Issue by dcolleoni** [Systemorph/IFRS17CalculationEngine#230]
1. Rename Nominal Cashflow csv
2. Remove all new Scopes in ReportScopes - discuss other changes
3. Reset most of ReporScopes, all ReporMutableScope
4. Cost reset Precision

- Test
- Create a test - focus on scenarios: for experienceAdjustments - CSM/LC/LoReCo - Financial Performance or KPIs

**Comment by amuolo** [comment]
@dcolleoni @tkukuljan I propose you to cancel the picture with excel charts and instead to have snapshots of our charts to explain the use case. Additionally, I would really like to have simple scopes and methods to produce these charts from the data imported so as to empower the user to play with it not only by looking at the tables. What do you think?

**Comment by dcolleoni** [comment]
Dear @amuolo, there is a need to go out with what we have to share the presentation to the audience of the demo. We can  improve this notebook in the future implementing something in the direction you describe.
Pls @tkukuljan, add an issue in the backlog to track the improvements described. Thanks!
