### ISSUE TITLE
Remove Validations from Yield Curve Queries

### ISSUE THREAD

**Issue by nnikolopoulos** [Systemorph/IFRS17CalculationEngine#382]
In Utils/Queries#locked-in and Utils/Queries#current the YieldCurveNotFound validation currently exists inside the methods LoadLockedInYieldCurveAsync and LoadCurrentYieldCurveAsync.

The conditions that trigger these validations should be reviewed and the validations should be extracted from the Queries.

Documentation could also be subsequently added to the Locked-In and Current sections for the yield curve.

(FYI: @dcolleoni)

**Comment by andrey-katz-systemorph** [comment]
I am not sure that this can be done without annoying repetition. First, the method LoadLockedInYieldCurve is invoked thrice in the code: ImportStorage, in ParameterReportQueries and in the Tests. The second problem has to do with the fact that you run this check for each datanode. Relocating this check in to the place where the query is performed, would mean running an extra loop.

@dcolleoni @nnikolopoulos
