### ISSUE TITLE
ReportHub

### ISSUE THREAD

**Issue by dcolleoni** [Systemorph/IFRS17CalculationEngine#434]
-Objective: Compute ReportVariable and return IDataCube<ReportVariable>
-Required Data Hubs: ReferenceDataHub(only some type (ReportingNode, others?)), ParameterHub(only FxParameter?),IfrsVariableHub)
-Computation: it requires ReportStorage (+called methods) and ReportScopes

Test:
Compute ReportVariable DataCube for a simple reportType (PV). 
Assert that the properties of the report variables are correctly populated (check the join, a prop from IfrsVar and one from GoC)
Compute ReportVariable DataCube for a complex ReportType (PnL)
Assert existence of variables.

**Comment by amuolo** [comment]
closed since PR #442 and #446 have introduced the report plugin configuration with working test and up-to-date concepts with data synch
